### ISSUE TITLE
filter_kwargs drops parameters when the target has **kwargs

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#174]
For example, take
```
def myfunc(**kwargs):
    return kwargs
```
Feeding this into `filter_kwargs` does the following:

```python
In [9]: mir_eval.util.filter_kwargs(myfunc, name='boo')
Out[9]: {}
```
when I would instead expect
```python
In [10]: myfunc(name='boo')
Out[10]: {'name': 'boo'}
```

That is, I think `filter_kwargs` should retain parameters if the target already has a slop dict.  Is there a reason not to do this?

This came up again in sonify, where `chords` and `chroma` both have slop dicts that should accept `time_frequency` parameters.

**Comment by craffel** [comment]
I don't see why not.  I guess the reason this isn't supported is that it is outside of the original intended scope of `filter_kwargs` (remove any keyword arguments that aren't explicitly defined in the provided function), because if a function has a kwarg slop dict you don't need to use `filter_kwargs` at all.  If you want to do this, do you know how to check programmatically whether a function has a kwarg slop dict or not?

**Comment by bmcfee** [comment]
> because if a function has a kwarg slop dict you don't need to use filter_kwargs at all.

Yup, but in my case, i'm applying this to functions that may or may not have kwargs, so it would be handy to detect it automatically.



> do you know how to check programmatically whether a function has a kwarg slop dict or not?

`inspect.getargspec(myfunc).keywords is not None` does the trick, though it seems to be deprecated.  I'll check to see if there's a six wrapper for this.

**Comment by bmcfee** [comment]
> I'll check to see if there's a six wrapper for this.

There isn't, so I just hacked up a `has_kwargs` function that uses six to determine which python we're on, and does the right thing accordingly.
