### ISSUE TITLE
interval validation: is empty okay?

### ISSUE THREAD

**Issue by bmcfee** [craffel/mir_eval#200]
I'm running into validation failures in some segment data due to [this check](https://github.com/craffel/mir_eval/blob/master/mir_eval/util.py#L708-L710).  I can't remember why we require non-empty intervals, but I don't think there's a technical reason for it in terms of div-by-zero errors in any of the metrics.  I suspect this came out of some of the weirder conversion errors in parsing the salami dataset.

Could we relax this check to instead fail only if `intervals[:, 1] < intervals[:, 0]` (negative duration) and throw a warning if they're equal?

**Comment by craffel** [comment]
Just to be clear, you're saying you want to change `<=` to `<` so that intervals with effectively "length zero" are considered valid?  I don't see why not, but playing devil's advocate, why would that ever be considered valid?  It doesn't make a lot of conceptual sense to me, but maybe there's a use-case for it I don't know of.

**Comment by bmcfee** [comment]
Right.  Thinking back about it, this was probably introduced to prevent multiple hits for duplicated boundaries.

You're right though; I think we should leave it as is.  I'll close this one out.
