### ISSUE TITLE
Inconsistency between mir_eval.beat.evaluate and its individual components

### ISSUE THREAD

**Issue by simondurand** [craffel/mir_eval#265]
There is a slight inconsistency between mir_eval.beat.evaluate and its individual components, such as mir_eval.beat.f_measure. E.g, the score will be different if it is computed by default through the general evaluate method or with the individual component.

```
import mir_eval
import numpy as np

b1 = np.array([1.0, 2.0, 4.0, 6.0, 7.0, 8.1, 10.0])
b2 = np.array([2.0, 4.2, 6.01, 7.02, 8.0, 9.5])

print(mir_eval.beat.f_measure(b1, b2))
print(mir_eval.beat.evaluate(b1, b2)['F-measure'])
```
Outputs:
```
>>> 0.461538461538
>>> 0.5
```
The reason is that the beats appearing before the 5th second are removed by default on the evaluate method (`reference_beats = util.filter_kwargs(trim_beats, reference_beats, **kwargs)`) but not on the individual components. It is not a major issue as it can be changed manually, but it seems to me this inconsistency might be confusing to people not paying too much attention on what is going on.

Is there a specific reason to have a different default behaviour between the different methods? Otherwise I would suggest keeping the same default behaviour.

**Comment by craffel** [comment]
Hi, this is intended.  Note that in all of the example usage docstrings we show calling the trim_beats function before the beat metric function http://craffel.github.io/mir_eval/#mir_eval.beat.f_measure We don't want to trim out the first 5 seconds in the individual beat functions, because they may already be trimmed before being passed to them, and then we'd trim twice.  We *do* want to trim them in `evaluate` because we actually have just loaded in the beats, so we know they aren't trimmed.
