### ISSUE TITLE
[QUESTION] About BASS and PEAQ, PESQ

### ISSUE THREAD

**Issue by loretoparisi** [craffel/mir_eval#330]
I run several MSS algorithms, [open-unmix](https://github.com/sigsep/open-unmix-pytorch),  [spleeter](https://github.com/deezer/spleeter), etc. for which we have evaluation metrics on the test sets with `mir_eval` scripts. Clearly this evaluation is based on a comparison of the extracted sources from reference sources and "_...attempt to measure the perceptual quality of the separation_" as stated in https://github.com/craffel/mir_eval/blob/master/mir_eval/separation.py
Assumed that in general perceptual evaluation of audio quality (`PEAQ`, `PESQ`, `PEQV`) in somewhat a standard, that is based on Psychoacoustics/perceptual features for for _objectively measuring perceived audio quality_ [(1)](https://github.com/stephencwelch/Perceptual-Coding-In-Python/blob/master/PEAQ.md), while for the [BASS](https://hal.inria.fr/inria-00544230/document) problem we consider the distortions between the estimated source and the reference source to compute the `SDR`, `SAR`, `SIR`, `SNR` metrics, can we define a relation among these different evaluations?
Specifically, if we would consider [PESQ](https://en.wikipedia.org/wiki/Perceptual_Evaluation_of_Speech_Quality) (Perceptual Evaluation of Speech Quality) for separated vocals, and [PEAQ](https://en.wikipedia.org/wiki/Perceptual_Evaluation_of_Audio_Quality) for mixed and accompaniment separated tracks, which considerations can be done of these two kind of evaluations?

Thank you.

**Comment by faroit** [comment]
we typically didn't use perceptual metrics such as PEAQ because the distortions from source separation methods are still huge compared to what we have in audio coding (for what PESQ and PEAQ was designed for). Maybe we can already run these these metrics on current SOTA methods but in any cases this would have to be validated against human listening tests which is lot of work and requires professional equipment. Furthermore the questions to be asked to distinguish between quality, interference and artifacts are important ones. Have a look at [this more recent paper](https://ieeexplore.ieee.org/abstract/document/8462325/).

**Comment by loretoparisi** [comment]
@faroit thanks a lot Fabian, yes infact I was thinking to do a specific research on that with a researcher in the psychoacoustics field supported by the right equipment :) And maybe this could lead to an implementation in `mir-eval` :)
Thank you very much for the indications, closing for now.
